### ISSUE TITLE
关于无法登录教师帐号的Bug及其解决方案

### ISSUE THREAD

**Issue by yht0511** [anwenhu/zhixuewang#75]
对于教师帐号,类`TeacherAccount`里的`set_base_info`方法会获取`advanced_info`,程序会向`
https://www.zhixue.com/paperfresh/api/common/getCurrentUser`发送GET请求并以JSON格式解析返回数据.
但利用浏览器调试工具可发现对此接口的访问会返回状态码403,本结果使用多个教师帐号测试后被确认并非特例.疑似因接口被取消或部分帐号未填写全部个人信息导致.
程序运行至'teacher.py'的第65行时由于403错误,`advanced_info`无法被解析为JSON格式,故报错,报错信息如下:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yht\AppData\Local\Programs\Python\Python310\lib\site-packages\zhixuewang\account.py", line 145, in login
    return TeacherAccount(session).set_base_info()
  File "C:\Users\yht\AppData\Local\Programs\Python\Python310\lib\site-packages\zhixuewang\teacher\teacher.py", line 66, in set_base_info
    adv_result = advanced_info.json()["result"]
  File "C:\Users\yht\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
解决方法相当简单:
在64行后添加如下代码:
```
if advanced_info.status_code!=200:
    return self
```
经测试,修改后问题成功解决.

**Comment by immoses648** [comment]
@MasterYuan418

**Comment by MasterYuan418** [comment]
PR #76 已解决

**Comment by immoses648** [comment]
#76
